<?php
/**
 * Limites dos correios
 *
 * @var $this \Bleez\Correios\Block\Adminhtml\Catalog\Product\Edit\CorreiosLimit
 */
?>

<script>


    require(['jquery'], function($){

        var limits = <?php echo $this->getLimitSizes(); ?>;

        var format = '<?php echo $this->getFormat(); ?>';

        $('#weight').parent().after('<div id="weightType" style="display: none; width: 100%"></div>');
        $('#weight').parent().after('<span id="weightLimit" style="display: none; width: 420px; float: right; color: #ff0000"></span>');
        $('#weight').on('change', function(e) {
            showWeightsAlerts();
        });

        showWeightsAlerts();

        var weightType = $('#attribute-weight-container').find('.admin__addon-suffix').children().text();

        if(weightType != 'kgs'){
            $('#weightType').html('O correios não aceita a unidade de peso '+weightType+' será assumido Kgs').show();
        };

        function showWeightsAlerts(){
            if(parseInt($('#weight').val()) > <?php echo $this->getLimitWeight(); ?>){
                $('#weightLimit').html('Limite maximo do tipo de frete do correios é de <?php echo $this->getLimitWeight(); ?>kg o frete não irá ser calculado para esse produto').show();
            }else{
                $('#weightLimit').hide()
            }
        }

        $('#largura').parent().append('<div id="larguraLimit" style="display: none; float: left; color: #ff0000"></div>');
        $('#largura').on('change', function(e) {
            showSizeAlert('largura', limits);
            showSomaLimit(format, limits);
        });

        $('#altura').parent().append('<div id="alturaLimit" style="display: none; float: left; color: #ff0000"></div>');
        $('#altura').on('change', function(e) {
            showSizeAlert('altura', limits);
            showSomaLimit(format, limits);
        });

        $('#comprimento').parent().append('<div id="comprimentoLimit" style="display: none; float: left; color: #ff0000"></div>');
        $('#comprimento').on('change', function(e) {
            showSizeAlert('comprimento', limits);
            showSomaLimit(format, limits);
        });

        function showSizeAlert(idElement, limits){
            if($('#'+idElement).val() < limits['minimo'][idElement]){
                $('#'+idElement+'Limit').html('Valor minimo de '+limits['minimo'][idElement]+' vai ser atribuido no calculo do frete');
                $('#'+idElement+'Limit').show();
                return;
            }
            if($('#'+idElement).val() > limits['maximo'][idElement]){
                $('#'+idElement+'Limit').html('Valor maximo de '+limits['maximo'][idElement]+ '! O frete dos correios não será calculado nesse produto');
                $('#'+idElement+'Limit').show();
                return;
            }
            $('#'+idElement+'Limit').hide();
        }

        if(format == 'cilindro'){
            $('#attribute-altura-container').hide();
            $('#attribute-largura-container').find('.label span').html('Diametro');
        }

        $('#attribute-largura-container').before('<div id="somaLimit" style="display: none; float: left; color: #ff0000; text-align: center; width: 100%"></div>');

        function showSomaLimit(format, limits){
            if(format != 'envelope'){
                if(format == 'caixa'){
                    if(parseFloat(parseFloat($('#altura').val()) + parseFloat($('#largura').val()) + parseFloat($('#comprimento').val())) > limits['maximo']['soma']){
                        $('#somaLimit').html('A soma das dimensões não pode ultrapassar de '+limits['maximo']['soma']+' o frete não será calculado para esse produto');
                        $('#somaLimit').show();
                    }else{
                        $('#somaLimit').hide();
                    }
                }
                if(format == 'cilindro'){
                    if((parseFloat($('#largura').val())*2) + parseFloat($('#comprimento').val()) > limits['maximo']['soma']){
                        $('#somaLimit').html('As dimensões não podem ultrapassar o calculo (2xDiametro)+comprimento = '+limits['maximo']['soma']+' o frete não será calculado para esse produto');
                        $('#somaLimit').show();
                    }else{
                        $('#somaLimit').hide();
                    }
                }
            }
        }

    });



</script>